use std::default;

use anyhow::{ensure, Context, Result};
use async_openai::types::{
    ChatCompletionRequestMessage, ChatCompletionRequestSystemMessageArgs,
    ChatCompletionRequestUserMessageArgs, ChatCompletionResponseMessage,
    CreateChatCompletionRequestArgs,
};

use inquire::{required, Text};
use regex::Regex;
use reqwest::Client;
use serde::Deserialize;
use tokio::process::Command;
use which::which;

/// Stores a single commit message candidate generated by the model
#[derive(Deserialize)]
struct CommitMessageCandidate {
    message: ChatCompletionResponseMessage,
}

/// Stores all the commit message candidates generated by the model
#[derive(Deserialize)]
struct CommitMessageCandidates {
    choices: Vec<CommitMessageCandidate>,
}

/// Asynchronously generates a commit message using the provided HTTP client, configuration, and Git differences.
///
/// Constructs a request payload for the API based on the provided configuration and staged Git differences.
/// Sends the request to the API provider, retrieves and parses the response, and extracts the generated
/// commit message. Post-processes the commit message to keep only the first line and remove leading and trailing backticks.
///
/// # Arguments
///
/// * `http_client` - A reference to the Reqwest HTTP client used to send requests to the API.
/// * `config` - A reference to the configuration containing API details, model information, and prompt contents.
/// * `diff` - A reference to the staged Git differences to be included in the user prompt.
///
/// # Returns
///
/// Returns a `Result` containing the generated commit message as a string on success,
/// or an error if there were issues constructing the request, sending it, or processing the response.
pub async fn generate_commit_summary(
    http_client: &Client,
    config: &crate::app_config::config::Config,
    diff: &str,
    file_text_list: Vec<String>,
) -> Result<String> {
    let mut chat_completion_request_system_message_args_list: Vec<ChatCompletionRequestMessage> =
        Vec::new();

    for file_text in file_text_list {
        chat_completion_request_system_message_args_list.push(
            ChatCompletionRequestSystemMessageArgs::default()
                .content(file_text)
                .build()?
                .into(),
        )
    }

    let payload = CreateChatCompletionRequestArgs::default()
        .max_tokens(config.max_chars)
        .model(&config.git_model_name)
        .messages(chat_completion_request_system_message_args_list)
        .build()
        .context("Failed to construct the request payload")?;

    let response = http_client
        .post(format!("{}/chat/completions", &config.git_api_base_url))
        .bearer_auth(&config.api_key)
        .json(&payload)
        .send()
        .await
        .context("Failed to send the request to the API provider")?
        .error_for_status()?
        .json::<CommitMessageCandidates>()
        .await
        .context("Failed to parse the response from the API provider")?;

    let commit_message = response
        .choices
        .first() // Only the first generated commit message is used
        .context("No commit messages generated")?
        .message
        .content
        .as_ref()
        .context("No commit messages generated")?;

    // Post-process the generated commit message to keep only the first line and remove leading and trailing backticks
    let regex_matches = Regex::new(r"(?m)^\s*(?:`\s*(.+?)\s*`|(.+?))\s*$")?
        .captures(commit_message)
        .context("Failed to post-process the generated commit message")?;

    let commit_message = regex_matches
        .get(1)
        .or(regex_matches.get(2))
        .context("Failed to post-process the generated commit message")?
        .as_str()
        .to_string();

    Ok(commit_message)
}

pub fn edit_commit_message(generated_commit_message: &str) -> Result<String> {
    // Ask user to edit the generated commit message if needed
    let edited_commit_message = Text::new("Your generated commit message:")
        .with_initial_value(&generated_commit_message)
        .with_validator(required!(
            "Please provide a commit message to create a commit"
        ))
        .with_help_message(
            "Press Enter to create a new commit with the current message or ESC to cancel",
        )
        .prompt()?;

    Ok(edited_commit_message)
}
